Fix crash when skipping an import
If we skipped a feed because it was already imported we returned None,
which it then tried to use as a string to summarise the actions taken.

Error was:

    Traceback (most recent call last):
      File "/home/tal/Projects/zero-install/0repo/0repo.py", line 10, in <module>
	cmd.main(sys.argv)
      File "/home/user/Projects/zero-install/0repo/repo/cmd/__init__.py", line 54, in main
	cmd.handle(args)
      File "/home/user/Projects/zero-install/0repo/repo/cmd/update.py", line 22, in handle
	do_update(config, messages)
      File "/home/user/Projects/zero-install/0repo/repo/cmd/update.py", line 51, in do_update
	config.upload_public_dir(files, message = ', '.join(messages))
    TypeError: sequence item 0: expected string, NoneType found